name: Automated Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.0

    # Step 3: Run Test 1: File with 10 numbers
    - name: Run Test 1: File with 10 numbers
      run: |
        python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
        diff test_data/test1_output.txt test_data/test1_expected.txt

    # Step 4: Run Test 2: File with 1 number
    - name: Run Test 2: File with 1 number
      run: |
        python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
        diff test_data/test2_output.txt test_data/test2_expected.txt

    # Step 5: Run Test 3: Blank file
    - name: Run Test 3: Blank file
      run: |
        python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
        diff test_data/test3_output.txt test_data/test3_expected.txt
